# name: publish

# on: [push]

# jobs:
#       publish-psv-image:
#             runs-on: ubuntu-latest
#             steps:
#                   - uses: action/checkout@v2
#                   - name: Login to github registry
#                     uses: docker/login-action@v2
#                     with:
#                      repository: Cyrof/password_manager_2.0
#                      token: ${{ secrets.GITHUB_TOKEN }}
#                      ref: master
#                   - name: Build psv image
#                     run: | 
#                         docker build . --tag ghcr.io/cyrof/psv:latest
#                         docker run ghrc.io/cyrof/psv:latest
#                         docker push ghrc.io/cyrof/psv:latest
name: publish

on: [push]

jobs:
  publish-psv-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the hello-world Docker image
      run: |
        echo $PSV2_PAT | docker login ghcr.io -u cyrof --password-stdin
        docker build . --tag ghcr.io/cyrof/psv:latest
        docker run -i ghcr.io/cyrof/psv:latest
        docker push ghcr.io/cyrof/psv:latest
      env:
        PSV2_PAT: ${{ secrets.PSV2_PAT }}
