name: publish

on: [push]

jobs:
runs-on: ubuntu-latest
steps:
- uses: action/checkout@v2
- name: Login to github registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build psv2 docker image
run: |
      docker build . --tag ghcr.io/cyrof/psv:latest
      docker run ghrc.io/cyrof/psv:latest
      docker push ghrc.io/cyrof/psv:latest
