name: publish

on: [push]

jobs:
      publish-psv-image:
            runs-on: ubuntu-latest
            steps:
                  - uses: action/checkout@v2
                  - name: Login to github registry
                        run: | 
                              docker build . --tag ghcr.io/cyrof/psv:latest
                              docker run ghrc.io/cyrof/psv:latest
                              docker push ghrc.io/cyrof/psv:latest
